version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24   # <--- use Node.js 20 runtime in CodeBuild
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://react-todo-deployment-app/ --delete
      - aws cloudfront create-invalidation --distribution-id EWLNGK8NKKLSG --paths "/*"
      - aws cloudfront create-invalidation --distribution-id E30NT0JKFJ7F1Q --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no

