version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24   # <--- use Node.js 20 runtime in CodeBuild
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  base-directory: build
  discard-paths: no
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
